version: '2'

services:
  nginx:
    build:
      context: ./..
      dockerfile: ./docker/nginx/Dockerfile
    env_file:
      - ./../.env
    ports:
      - '80:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./..:/code

  php-fpm:
    build:
      context: ./..
      dockerfile: ./docker/php-fpm/Dockerfile
    env_file:
      - ./../.env
    volumes:
      - ./..:/code

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
    env_file:
      - ./../.env
    ports:
      - '3306:3306'
    volumes:
      - ./data/mysql:/var/lib/mysql
